### ISSUE TITLE
promiseWithDuration is needed

### ISSUE THREAD

**Issue by gerchicov-bp** [PromiseKit/EZiOS7#3]
It exists in main PromiseKit 2.0 repository but that whole library supports iOS 8 only. Could you add this feature?

**Comment by mxcl** [comment]
It's in the Categories directory, you have to add it manually, see the README for instructions.

**Comment by gerchicov-bp** [comment]
Sorry I have tangled more. Is EZiOS7 just a wrapper over PromiseKit 2.0 to support iOS7?

**Comment by mxcl** [comment]
No, it combines all the sources into as few as possible so that you can drag and drop them into an iOS 7 project. Otherwise adding PromiseKit to an iOS 7 project is hard, but not impossible.

It doesn't bundle any of the category functions, you have to drag and drop those in addition to the PromiseKit.* sources from the Categories directory.

**Comment by mxcl** [comment]
Closing, but feel free to ask more questions.

**Comment by gerchicov-bp** [comment]
Thanks but I've found out a more appropriate library for me - RZViewActions
